version: '3'

services:
  web:
    build: ./web
    image: pbot-web:latest
    restart: always
    ports:
      - "80:4000"
    environment:
      - DEBUG=*,-web:*
    volumes:
      - ./data:/www/data
  mongo:
    image: mongo:4-xenial
    restart: always
    expose:
      - '27017'
    command: '--smallfiles'
    volumes:
      - ./db:/data/db
